requirements/pkg-deps.txt, src/js/package.json
The IDOM client and core libraries now have synchronized versions. To ensure they work correctly together we need to ensure the version requirements we use both are the same.
=> synchronize JS and Py version requirements for IDOM

tests/test_app/tests.py
Last test run failed due to timeout, but it succeeded upon repeating the test run workflow.
Might be related to the time it takes the channels development webserver to start up.
This PR increases the timeout values within our tests to reduce the chance of this happening.
=> increase test timeout

README.md
Example shows `IDOM_WEB_MODULES_PATH`, when it should be `IDOM_WEBSOCKET_PATH`.
=> fix websocket example

src/django_idom/paths.py, src/django_idom/views.py
Adding `name=...` to our paths allows for developers to use [django reverse](https://docs.djangoproject.com/en/3.2/ref/urlresolvers/#reverse) to obtain these URLs via name.
=> Add "name" to WS and Web Module paths

.github/workflows/test.yml, README.md, requirements/pkg-deps.txt, setup.py, src/django_idom/config.py, src/django_idom/views.py
- [Use Django async caching API](https://docs.djangoproject.com/en/4.0/topics/cache/#asynchronous-support)
- Note: This limits us to Django 4.0+, Python 3.8+.
- Remove async_lru_cache.
- [Django's default cache engine is functionally equivalent](https://docs.djangoproject.com/en/4.0/topics/cache/#local-memory-caching).
- Fix #46 
- Use [`aiofile`](https://github.com/mosquito/aiofile) for async file operations.
- Protect against malicious file paths (ex `../../../etc/passwd`)
- [Use cache versioning to invalidate old web module files stored in cache](https://docs.djangoproject.com/en/4.0/topics/cache/#cache-versioning)
=> Improve Caching Schema

src/django_idom/__init__.py, src/js/package-lock.json, src/js/package.json
This PR prepares Django IDOM for a new PyPI release.
=> Django IDOM v0.0.2

README.md, src/django_idom/config.py, src/django_idom/templates/idom/component.html, src/django_idom/templatetags/idom.py
Changes the `IDOM_WS_MAX_RECONNECT_DELAY` setting to be more appropriately named
=> IDOM_WS_MAX_RECONNECT_DELAY -> IDOM_WS_MAX_RECONNECT_TIMEOUT

.github/workflows/publish-js.yml, .github/workflows/publish-py.yml, requirements/build-pkg.txt
=> Publishing CI Workflow

README.md
I got some input on the readme structure from some new Django developers.
This PR does some minor touchups to the readme to be more beginner friendly.
=> Beginner friendly readme

README.md
For the readme example we currently use `html.header` which doesn't make much sense.
This PR replaces it with `html.h1`
=> header -> h1

CHANGELOG.md, src/django_idom/__init__.py, src/js/package.json
Related to breaking changes introduced by https://github.com/idom-team/idom/discussions/680
=> bump min client requirement

CHANGELOG.md, src/js/package-lock.json, src/js/package.json
We forgot to bump `django-idom-client`.
We should think of some way of automating this, even if it's just a simple python script that manually edits all these values through regex.
=> Fix 0.0.3 Publishing

src/django_idom/http/views.py
`Path.absolute()` is undocumented and not tested with all operating systems. Therefore, this PR replaces it with `os.path.abspath()`
Note: `Path.resolve()` cannot be used due to it following symlinks on POSIX operating systems.
=> Replace Path.absolute with os.path.abspath

CHANGELOG.md, src/django_idom/components.py
I accidentally commited a script I was using to test ShadowDOM when incorporating the review on PR #78.
=> Remove misc script from django_css

docs/features/components.md, docs/features/orm.md, docs/getting-started/render-view.md
Noticed one minor typo in the docs for `django_js`
-   [x] The `changelog.rst` has been updated with any significant changes, if necessary.
=> Fix some example in docs

MANIFEST.in, noxfile.py, pyproject.toml, requirements/check-types.txt, src/django_idom/http/urls.py, src/django_idom/py.typed, src/django_idom/utils.py
Check that our type annotations are correct. This should also help us reproduce type annotation issues in future pull requests.
-   [ ] The `changelog.rst` has been updated with any significant changes, if necessary.
-   [ ] GitHub Issues which may be closed by this PR have been linked.
=> check mypy

CHANGELOG.md, src/django_idom/utils.py, tests/test_app/tests/test_regex.py
I realized some handlebars formatters will add indentation and newlines. Therefore, I've made the component regex a bit more robust to handle those situations.
-   [X] Tests have been included for all bug fixes or added functionality.
-   [x] The `changelog.rst` has been updated with any significant changes, if necessary.
-   [X] GitHub Issues which may be closed by this PR have been linked.
=> Allow whitespace characters within component regex

CHANGELOG.md, requirements/test-env.txt, src/django_idom/utils.py, tests/test_app/tests/test_components.py, tests/test_app/tests/test_regex.py
- fix #102
- fix #14 
-   [x] The `changelog.rst` has been updated with any significant changes, if necessary.
=> Fix IDOM preloader trying to parse commented out HTML templates

src/django_idom/http/views.py
Django stubs has been updated to support some parts of Django >4, thus some `# type: ignore` statements are no longer needed.
-   [X] Tests have been included for all bug fixes or added functionality.
-   [X] The `changelog.rst` has been updated with any significant changes, if necessary.
-   [X] GitHub Issues which may be closed by this PR have been linked.
=> django-stubs 1.13.0 compatibility

CHANGELOG.md, src/reactpy_django/apps.py, tests/test_app/asgi.py
Removes `db_cleanup` from startup, as it can cause issues with how the `uvicorn` CLI runs. Technically it wasn't needed to run on startup in the first place, as the cleanup will run on first websocket connect anyways.
I haven't detected this issue before since Conreq uses uvicorn's python interface rather than CLI.
This can be seen by doing the following:
1) `cd tests`
2) `uvicorn test_app.asgi:application`
-   [x] The changelog has been updated with any significant changes, if necessary.
=> Remove `db_cleanup` from startup

CHANGELOG.md, README.md
Change `similarly` to `similar` to be gramatically correct.
-   [x] The changelog has been updated with any significant changes, if necessary.
=> Fix grammar in readme

CHANGELOG.md, README.md, docs/src/changelog/index.md, docs/src/contribute/code.md, docs/src/contribute/docs.md, docs/src/contribute/running-tests.md, docs/src/features/components.md, docs/src/features/decorators.md, docs/src/features/hooks.md, docs/src/features/settings.md, docs/src/features/template-tag.md, docs/src/features/utils.md, docs/src/get-started/choose-django-app.md, docs/src/get-started/create-component.md, docs/src/get-started/installation.md, docs/src/get-started/learn-more.md, docs/src/get-started/register-view.md, docs/src/get-started/run-webserver.md, docs/src/get-started/use-template-tag.md, docs/src/stylesheets/extra.css, mkdocs.yml
Minor styling and verbiage tweaks to ensure consistency between:
- ReactPy Core <-> ReactPy-Django.
- ReactJS Beta Docs <-> ReactPy-Django
-   [ ] Tests have been included for all bug fixes or added functionality.
-   [ ] The changelog has been updated with any significant changes, if necessary.
-   [ ] GitHub Issues which may be closed by this PR have been linked.
=> Docs and readme tweaks

CHANGELOG.md, src/reactpy_django/utils.py, src/reactpy_django/websocket/consumer.py
Added warning on poor system/cache/database performance. This is detected when ReactPy-Django takes longer than one second to perform a `db_cleanup`
Ref: https://github.com/reactive-python/reactpy-django/discussions/128
-   [ ] Tests have been included for all bug fixes or added functionality.
-   [x] The changelog has been updated with any significant changes, if necessary.
=> Add warning if poor performance is detected

CHANGELOG.md, docs/python/configure-asgi-middleware.py, docs/python/configure-asgi.py, docs/python/settings.py, docs/src/features/decorators.md, docs/src/get-started/installation.md, requirements/pkg-deps.txt, requirements/test-env.txt, src/reactpy_django/config.py, src/reactpy_django/websocket/consumer.py, tests/test_app/settings.py
- Added `REACTPY_AUTH_BACKEND` setting to allow for custom authentication backends.
- Refactor the websocket consumer so that using `SessionMiddlewareStack` and/or `AuthMiddlewareStack` is now optional.
- Make Django a mandatory project dependency, since we need Django 4.1+
-   [X] The changelog has been updated with any significant changes, if necessary.
-   [X] GitHub Issues which may be closed by this PR have been linked.
=> Add `REACTPY_AUTH_BACKEND` setting

CHANGELOG.md, src/reactpy_django/__init__.py
*By submitting this pull request you agree that all contributions to this project are made under the MIT license.*
Forgot to bump versions in the previous PR. Should have gotten more sleep the night before 😓.
=> 3.3.2 Version Bump

.github/workflows/publish-develop-docs.yml, .github/workflows/publish-release-docs.yml
*By submitting this pull request you agree that all contributions to this project are made under the MIT license.*
Mike requires a `git.user` otherwise it will fail to deploy.
ref: https://github.com/jimporter/mike/issues/49
=> Add git user to mike deployment

CHANGELOG.md, README.md, src/reactpy_django/checks.py
*By submitting this pull request you agree that all contributions to this project are made under the MIT license.*
A summary of the changes.
-   [x] The changelog has been updated with any significant changes, if necessary.
=> Warn if `INSTALLED_APPS['reactpy_django']` position looks suspicious

README.md, docs/overrides/home-code-examples/add-interactivity-demo.html, docs/src/assets/css/navbar.css
*By submitting this pull request you agree that all contributions to this project are made under the MIT license.*
Add "No Match" text to interactive demo on the homepage
=> Add "No Match" text to interactive demo

docs/src/about/code.md, docs/src/assets/css/admonition.css, docs/src/assets/css/sidebar.css, docs/src/assets/css/table-of-contents.css, docs/src/learn/add-reactpy-to-a-django-project.md, docs/src/learn/your-first-component.md, docs/src/reference/hooks.md, docs/src/reference/settings.md, docs/src/reference/template-tag.md, mkdocs.yml, src/reactpy_django/templatetags/reactpy.py
- Redesign docs settings page
- Misc docs tweaks
<sub>By submitting this pull request you agree that all contributions comply with this project's open source license(s).</sub>
=> Redesign docs settings page

.github/FUNDING.yml, .github/workflows/publish-py.yml, .github/workflows/test-src.yml, docs/src/about/code.md, pyproject.toml, requirements/test-env.txt, setup.py, tests/test_app/__init__.py
Our test suite currently relies on the user manually installing `NodeJS` in order for `npm` commands to be run.
This is an error prone process with way to control what `npm` version the end-user has. This method also can also fail due to missing `PATH` variables.
This PR uses premade binaries for `npm` instead of the user's local `npm` installation.
-   [ ] Tests have been developed for bug fixes or new functionality.
-   [ ] The changelog has been updated, if necessary.
-   [ ] Documentation has been updated, if necessary.
-   [ ] GitHub Issues closed by this PR have been linked.
<sub>By submitting this pull request you agree that all contributions comply with this project's open source license(s).</sub>
=> Use `NodeJS-bin` instead of the user's `node` install

README.md
Modify the readme to add top features
=> Add list of top features to the readme

.github/workflows/publish-develop-docs.yml, .github/workflows/publish-py.yml, .github/workflows/publish-release-docs.yml, .github/workflows/test-docs.yml, .github/workflows/test-src.yml, CHANGELOG.md, README.md, docs/mkdocs.yml, docs/src/about/code.md, docs/src/about/docs.md, noxfile.py, requirements/check-style.txt, setup.py, src/js/package-lock.json, src/js/package.json, src/js/rollup.config.mjs, src/js/src/client.ts, src/js/src/index.tsx, src/js/src/types.ts, src/js/src/utils.ts, src/js/tsconfig.json
Changes need to make https://github.com/reactive-python/reactpy-router/pull/29 match up with the this repo.
=> Refactor repo to match ReactPy Router

src/reactpy_django/templates/reactpy/component.html
No functional changes, just making the template tag HTML more visually compact
=> More compact template tag HTML

docs/examples/python/use-channel-layer-group.py, docs/examples/python/use-channel-layer-signal-sender.py, docs/src/reference/hooks.md, src/reactpy_django/hooks.py, tests/test_app/channel_layers/components.py
Minor follow up to #221 PR to tweak the user API.
=> Tweak `use_channel_layer` to allow custom group channel names

CHANGELOG.md, docs/examples/python/use-root-id.py, docs/src/reference/hooks.md, src/reactpy_django/hooks.py, src/reactpy_django/models.py, src/reactpy_django/templatetags/reactpy.py, src/reactpy_django/websocket/consumer.py, src/reactpy_django/websocket/paths.py, tests/test_app/prerender/components.py, tests/test_app/templates/prerender.html, tests/test_app/tests/test_components.py, tests/test_app/tests/test_database.py
Create a `use_root_id` hook that fetches this value from the websocket or HTTP connection
- fix #203
- Some miscellaneous refactoring on the websocket `consumer` and `UserDataModel`, just because I happened to notice some cleanup potential while making this PR.
=> `use_root_id` hook

CHANGELOG.md, docs/examples/python/django-query-postprocessor.py, docs/examples/python/use-mutation-query-refetch.py, docs/examples/python/use-mutation-thread-sensitive.py, docs/examples/python/use-query-args.py, docs/examples/python/use-query-postprocessor-change.py, docs/examples/python/use-query-postprocessor-disable.py, docs/examples/python/use-query-postprocessor-kwargs.py, docs/examples/python/use-query-thread-sensitive.py, docs/examples/python/use-query.py, docs/includes/orm.md, docs/src/reference/hooks.md, src/reactpy_django/hooks.py, src/reactpy_django/types.py, src/reactpy_django/utils.py, src/reactpy_django/websocket/consumer.py, tests/test_app/components.py
=> New `use_query` and `use_mutation` API

.github/workflows/test-docs.yml, .gitignore, .linkspector.yml, requirements/build-docs.txt, src/reactpy_django/clean.py
- Fix python tests failures caused by upgraded mypy stubs
- Switch `linkcheckmd` to it's replacement `linkspector`
- `linkcheckmd` needs to be removed because `ReadTheDocs` has started to blacklist GitHub workflow IPs, and `linkcheckmd` has no configuration for excluding URL patterns. 
- As a note, it looks like the the latest version of the `linkspector` workflow has broken directory scanning. Am going to move forward with this PR anyways in the hopes that it gets fixed soon.
<sub>By submitting this …
=> Fix Python and docs tests

.github/workflows/publish-py.yml
PyPi publishing is currently broken due to dependency issues, but I'm using this as an opportunity to try the `hatch publish` command instead.
=> Attempt using hatch publish command

.github/workflows/publish-py.yml
Looks I misused the `HATCH_INDEX_REPO` environment variable. I don't believe it's mandatory so will be testing publishing with it removed.
-   [ ] Tests have been developed for bug fixes or new functionality.
-   [ ] The changelog has been updated, if necessary.
-   [ ] Documentation has been updated, if necessary.
-   [ ] GitHub Issues closed by this PR have been linked.
=> Remove HATCH_INDEX_REPO from CI

CHANGELOG.md, tests/test_app/tests/js/button-from-js-module.js, tests/test_app/tests/test_components.py
Accidentally forgot a changelog header in the last PR.
=> Add missing changelog header

.github/workflows/codeql.yml, tests/test_app/forms/components.py, tests/test_app/forms/forms.py, tests/test_app/tests/test_components.py, tests/test_app/tests/utils.py
Simplify bootstrap form tests to reduce test runner time.
=> Simplify bootstrap form tests

docs/examples/python/django_router.py, docs/examples/python/use_mutation.py, docs/examples/python/use_mutation_query_refetch.py, docs/examples/python/use_mutation_reset.py, docs/examples/python/use_mutation_thread_sensitive.py, docs/examples/python/use_query_refetch.py, docs/examples/python/use_user_data.py, docs/src/reference/hooks.md, docs/src/reference/router.md, tests/test_app/components.py, tests/test_app/performance/components.py, tests/test_app/pyscript/components/child.py, tests/test_app/pyscript/components/counter.py
Fix a couple typos in the docs, add some additional clarity to the mutation/query docs, and switch to using `camelCase` for prop names.
-   [ ] Tests have been developed for bug fixes or new functionality.
-   [ ] The changelog has been updated, if necessary.
-   [ ] Documentation has been updated, if necessary.
-   [ ] GitHub Issues closed by this PR have been linked.
=> Fix docs typos
